
AWSTemplateFormatVersion: "2010-09-09"
Description: This template creates the deployment of a web server,s3 bucket for cloudwatch log archival, IAM role for cloudwatch agent and SSM and VPC
Parameters: 
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  DisplayedName: 
    Description: Name displayed on the web page
    Type: String
    Default: Ada 
    AllowedPattern: "[a-zA-Z]*"
  BucketName:
    Type: String
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    Description: S3 bucket for log files
Resources:
  EC2Instance: 
    Type: AWS::EC2::Instance
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          # install HTTPD (apache web server) and PHP for this instance using yum
          packages:
            yum:
              httpd: []
              php: []
          # creates a file in tmp called test.php that is a simple "hello world"
          files:
            /var/www/html/index.php:
              content: !Join 
                - ''
                - - |
                    <?php
                  - |
                    echo '<h1>This website is made by     
                  - !Ref DisplayedName
                  -  </h1>';
                  - |
                    ?>
              mode: '000644'
              owner: apache
              group: apache
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
    Properties:
      InstanceType: t2.micro
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref LatestAmiId
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          GroupSet: 
            - !Ref InstanceSecurityGroup
          SubnetId: !Ref PublicSubnet
          DeviceIndex:  '0'
          DeleteOnTermination: true
      Tags:
          - Key: Workload
            Value: Security-Lab
          - Key: Name
            Value: Security-Lab-Instance
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              # installs cfn-bootstrap using yum
              yum install -y aws-cfn-bootstrap
            - |
              # Install the files and packages from the metadata
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource EC2Instance '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+

            - |
              # Signal the status from cfn-init
            - '/opt/aws/bin/cfn-signal -e $? '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource EC2Instance '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+
          
    CreationPolicy:
      ResourceSignal: 
        Timeout: PT5M
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enables SSH via port 22, HTTP via port 80
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  CloudWatchIAMRole:
    Type: AWS::IAM::Role
    Properties:
      Description: IAM role used to enable CloudWatch Agent and SSM usage for the EC2 Instance
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref CloudWatchIAMRole
  S3LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
            BlockPublicAcls : true
            BlockPublicPolicy : true
            IgnorePublicAcls : true
            RestrictPublicBuckets : true
      Tags:
          - Key: Workload
            Value: Security-Lab
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3LogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Action: s3:GetBucketAcl 
            Effect: Allow
            Resource: !GetAtt S3LogBucket.Arn
            Principal: 
              Service: !Join
                - ""
                - 
                  - "logs."
                  - !Ref AWS::Region
                  - ".amazonaws.com"
          -
            Action: s3:PutObject
            Effect: Allow
            Resource: !Join
              - ""
              - 
                - !GetAtt S3LogBucket.Arn
                - "/lablogs/*"
            Principal:
              Service: !Join
                - ""
                - 
                  - "logs."
                  - !Ref AWS::Region
                  - ".amazonaws.com"
  VPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key : Workload
          Value : Security-Lab
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: '10.0.0.0/24'
      VpcId: !Ref 'VPC'
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - '0'
        - !GetAZs 
      Tags:
        - Key : Workload
          Value : Security-Lab 
  IGW:
    Type: AWS::EC2::InternetGateway
  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref 'VPC'
      InternetGatewayId: !Ref 'IGW'
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref 'VPC'
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref 'PublicRouteTable'
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'IGW'
  PublicSubnetOneRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable
    


Outputs:
  WebsiteURL:
    Description: Application URL
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - EC2Instance
          - PublicDnsName
  EC2InstanceID:
      Description: ID of the EC2 Instance
      Value: !Ref EC2Instance